apps/coding/coding/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^show/(?P<product_id>\d+)/$', views.show, name="show"),
  url(r'^edit/(?P<product_id>\d+)/$', views.edit, name="edit"),
  url(r'^update/(?P<product_id>\d+)/$', views.update, name="update"),
  url(r'^delete/(?P<product_id>\d+)/$', views.delete, name="delete"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  # url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^login/$', views.login, name="login"),
  url(r'^logout/$', views.logout, name="logout"),
  # url(r'^show/(?P<user_id>\d+)/$', views.show, name="show"),
  # url(r'^edit/(?P<user_id>\d+)/$', views.edit, name="edit"),
  # url(r'^update/(?P<user_id>\d+)/$', views.update, name="update"),
  # url(r'^delete/(?P<user_id>\d+)/$', views.delete, name="delete"),
]

bye/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace="users")),
    url(r'^orders/', include('apps.orders.urls', namespace="orders")),
    url(r'^', include('apps.products.urls', namespace="products")),
]

apps/users/models.py
from django.db import models
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.
class UserManager(models.Manager):
  def validate(self, form_data):
    errors = []

    if len(form_data['first_name']) < 3:
      errors.append("First name must be at least 3 characters")
    if len(form_data['last_name']) < 3:
      errors.append("Last name must be at least 3 characters")
    if len(form_data['password']) < 8:
      errors.append("Password must be at least 8 characters")
    if not EMAIL_REGEX.match(form_data['email']):
      errors.append("Email must be valid")

    existing_users = self.filter(email=form_data['email'])
    if existing_users:
      errors.append("Email already in use")

    return errors

  def create_user(self, form_data):
    pw_hash = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
    return self.create(
      first_name=form_data['first_name'],
      last_name=form_data['last_name'],
      email=form_data['email'],
      pw_hash=pw_hash,
    )

  def login(self, form_data):
    existing_users = self.filter(email=form_data['email'])
    if not existing_users:
      return (False, 'Email or password invalid')

    user = existing_users[0]
    if bcrypt.checkpw(form_data['password'].encode(), user.pw_hash.encode()):
      return (True, user)
    else:
      return (False, 'Email or password invalid')


class User(models.Model):
  first_name = models.CharField(max_length=255)
  last_name = models.CharField(max_length=255)
  email = models.CharField(max_length=255)
  pw_hash = models.CharField(max_length=500)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = UserManager()

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

# Create your views here.
def new(req):
  return render(req, 'users/new.html')

def create(req):
  errors = User.objects.validate(req.POST)
  if errors:
    for error in errors:
      messages.error(req, error)
    return redirect('users:new')
  user = User.objects.create_user(req.POST)
  req.session['user_id'] = user.id
  return redirect('products:index')

def login(req):
  valid, result = User.objects.login(req.POST)
  if not valid:
    messages.error(req, result)
    return redirect('users:new')
  else:
    req.session['user_id'] = result.id
  return redirect('products:index')

def logout(req):
  req.session.clear()
  return redirect('users:new')

apps/users/templates/users/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>Login or Register</h1>
    {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
    <h2>Register</h2>

    <form action="{% url 'users:create' %}" method="post">
      {% csrf_token %}
      <label for="first_name">Fist Name:</label>
      <input type="text" name="first_name" value="">

      <label for="last_name">Last Name:</label>
      <input type="text" name="last_name" value="">

      <label for="email">Email:</label>
      <input type="text" name="email" value="">

      <label for="password">Password:</label>
      <input type="password" name="password" value="">

      <input type="submit" name="Register" value="Submit">
    </form>
    <h2>Login</h2>
    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      <label for="email">Email:</label>
      <input type="text" name="email" value="">

        <label for="password">Password:</label>
        <input type="password" name="password" value="">

      <input type="submit" name="Login" value="Submit">
    </form>
  </div>
  </body>
</html>