apps/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name="index"),
  url(r'^cart/$', views.cart, name="cart"),
  url(r'^add_product/$', views.add_product, name="add_product"),
  url(r'^place_order/$', views.place_order, name="place_order")
]

apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^show/(?P<product_id>\d+)/$', views.show, name="show"),
  url(r'^edit/(?P<product_id>\d+)/$', views.edit, name="edit"),
  url(r'^update/(?P<product_id>\d+)/$', views.update, name="update"),
  url(r'^delete/(?P<product_id>\d+)/$', views.delete, name="delete"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  # url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^login/$', views.login, name="login"),
  url(r'^logout/$', views.logout, name="logout"),
  # url(r'^show/(?P<user_id>\d+)/$', views.show, name="show"),
  # url(r'^edit/(?P<user_id>\d+)/$', views.edit, name="edit"),
  # url(r'^update/(?P<user_id>\d+)/$', views.update, name="update"),
  # url(r'^delete/(?P<user_id>\d+)/$', views.delete, name="delete"),
]

bye/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace="users")),
    url(r'^orders/', include('apps.orders.urls', namespace="orders")),
    url(r'^', include('apps.products.urls', namespace="products")),
]

apps/orders/models.py
from django.db import models
from ..users.models import User
from ..products.models import Product

# Create your models here.
class OrderManager(models.Manager):
  def add_product(self, form_data, user_id):
    # cart is the current order, cart is an Order object
    cart = self.get_active_cart(user_id)
    product = Product.objects.get(id=form_data['product_id'])
    # check to see if order already has at least one of current product attached
    attached_products = cart.order_products.filter(product=product.id)
    print(attached_products)
    if attached_products:
      order_item = attached_products[0]
      order_item.amount += 1
      order_item.save()
    else:
      OrderProduct.objects.create(
        product = product,
        order = cart,
        amount = 1
      )
    product.num_available -= 1
    product.save()
    return

  def get_active_cart(self, user_id):
    active_orders = self.filter(user=user_id).filter(in_progress=False)
    if active_orders:
      cart = active_orders[0]
    else:
      cart = self.create_default_order(user_id)
    return cart

  def create_default_order(self, user_id):
    user = User.objects.get(id=user_id)
    return self.create(
      is_fulfilled = False,
      in_progress = False,
      user = user,
    )

  def place_order(self, order_id, user_id):
    order = self.get(id=order_id)
    order.in_progress = True
    order.save()
    self.create_default_order(user_id)
    return

class Order(models.Model):
  is_fulfilled = models.BooleanField()
  in_progress = models.BooleanField()
  user = models.ForeignKey(User, related_name="orders")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = OrderManager()

class OrderProductManager(models.Manager):
  pass

class OrderProduct(models.Model):
  product = models.ForeignKey(Product, related_name="order_products")
  order = models.ForeignKey(Order, related_name="order_products")
  amount = models.IntegerField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

apps/orders/views.py
from django.shortcuts import render, redirect
from .models import Order

# Create your views here.
def index(req):
  context = {
    'orders': Order.objects.filter(user=req.session['user_id']).filter(in_progress=True)
  }
  return render(req, 'orders/index.html', context)

def cart(req):
  cart = Order.objects.filter(user=req.session['user_id']).filter(
      in_progress=False)[0]
  clean_data = []
  total = 0
  for order_product in cart.order_products.all():
    item = {
      'item': order_product.product.name,
      'price': order_product.product.price,
      'amount': order_product.amount,
      'subtotal': order_product.amount * order_product.product.price
    }
    total += item['subtotal']
    clean_data.append(item)

  context = {
    'cart': clean_data,
    'total': total,
    'order_id': cart.id
  }
  return render(req, 'orders/cart.html', context)

def add_product(req):
  Order.objects.add_product(req.POST, req.session['user_id'])
  return redirect('products:index')

def place_order(req):
  Order.objects.place_order(req.POST['order_id'], req.session['user_id'])
  return redirect('orders:index')

apps/orders/templates/orders/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>Your Cart</h1>
    <a href="{% url 'products:index' %}" class="button">Home</a>
    <a href="{% url 'users:logout' %}" class="button">Logout</a>
    <table>
      <thead>
        <tr>
          <th>Product Name</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Subtotal</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart %}
          <tr>
            <td>{{ item.item }}</td>
            <td>${{ item.price }}</td>
            <td>{{ item.amount }}</td>
            <td>${{ item.subtotal }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p>Total: ${{ total }}</p>
    <form action="{% url 'orders:place_order' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="order_id" value="{{ order_id }}">
      <input type="submit" value="Place Order">
    </form>
  </div>
</body>
</html>

apps/orders/templates/orders/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>All Orders</h1>
    <a href="{% url 'products:index' %}" class="button">Home</a>
    <a href="{% url 'users:logout' %}" class="button">Logout</a>
    <table>
      <thead>
        <tr>
          <th>Order Number</th>
          <th>In Progress</th>
          <th>Fulfilled</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.in_progress }}</td>
            <td>{{ order.is_fulfilled }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</body>
</html>