apps/coding/coding/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

apps/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name="index"),
  url(r'^cart/$', views.cart, name="cart"),
  url(r'^add_product/$', views.add_product, name="add_product"),
  url(r'^place_order/$', views.place_order, name="place_order")
]

apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^show/(?P<product_id>\d+)/$', views.show, name="show"),
  url(r'^edit/(?P<product_id>\d+)/$', views.edit, name="edit"),
  url(r'^update/(?P<product_id>\d+)/$', views.update, name="update"),
  url(r'^delete/(?P<product_id>\d+)/$', views.delete, name="delete"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  # url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^login/$', views.login, name="login"),
  url(r'^logout/$', views.logout, name="logout"),
  # url(r'^show/(?P<user_id>\d+)/$', views.show, name="show"),
  # url(r'^edit/(?P<user_id>\d+)/$', views.edit, name="edit"),
  # url(r'^update/(?P<user_id>\d+)/$', views.update, name="update"),
  # url(r'^delete/(?P<user_id>\d+)/$', views.delete, name="delete"),
]

bye/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace="users")),
    url(r'^orders/', include('apps.orders.urls', namespace="orders")),
    url(r'^', include('apps.products.urls', namespace="products")),
]

apps/products/models.py
from django.db import models
from ..users.models import User
from decimal import *

# Create your models here.
class ProductManager(models.Manager):
  def validate(self, form_data):
    errors = []

    if len(form_data['name']) < 2:
      errors.append('Name must be at least 2 characters long.')

    try:
      num_available = int(form_data['num_available'])
      if num_available < 1:
        errors.append('Must have at least 1 item in stock.')
    except:
      errors.append('Items in stock must be a number.')

    try:
      price = Decimal(form_data['price']).quantize(Decimal('.01'), rounding=ROUND_DOWN)
      if price < 0.01:
        errors.append('Product must cost money.')
    except:
      errors.append('Price must be a valid format.')

    if len(form_data['description']) < 1:
      errors.append('Must include a description')

    return errors

  def create_product(self, form_data, user_id):
    price = Decimal(form_data['price']).quantize(Decimal('.01'), rounding=ROUND_DOWN)
    num_available = int(form_data['num_available'])
    user = User.objects.get(id=user_id)
    self.create(
      name=form_data['name'],
      price=price,
      num_available=num_available,
      description=form_data['description'],
      creator=user,
    )

  def update(self, form_data, product_id):
    product = self.get(id=product_id)

    price = Decimal(form_data['price']).quantize(Decimal('.01'), rounding=ROUND_DOWN)

    product.name = form_data['name']
    product.num_available = int(form_data['num_available'])
    product.price = price
    product.description = form_data['description']
    product.save()

class Product(models.Model):
  name = models.CharField(max_length=255)
  num_available = models.IntegerField()
  price = models.DecimalField(max_digits=10, decimal_places=2)
  description = models.TextField()
  creator = models.ForeignKey(User, related_name="products")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = ProductManager()

apps/products/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .models import Product
from ..users.models import User

# Create your views here.
def index(req):
  if 'user_id' not in req.session:
    return redirect('users:new')

  context = {
    'purchasable_products': Product.objects.exclude(creator=req.session['user_id']).exclude(num_available__lte=0),
    'user': User.objects.get(id=req.session['user_id']),
  }
  return render(req, 'products/index.html', context)

def new(req):
  return render(req, 'products/new.html')

def show(req, product_id):
  if 'user_id' not in req.session:
    return redirect('users:new')

  try:
    context = {
      'product': Product.objects.get(id=product_id)
    }
  except ObjectDoesNotExist:
    return redirect('products:index')

  return render(req, 'products/show.html', context)

def edit(req, product_id):
  if 'user_id' not in req.session:
    return redirect('users:new')

  # TODO - Implement validation so only owners of the product can access the edit page.

  try:
    context = {
      'product': Product.objects.get(id=product_id)
    }
  except ObjectDoesNotExist:
    return redirect('products:index')

  return render(req, 'products/edit.html', context)

def create(req):
  errors = Product.objects.validate(req.POST)
  if errors:
    for error in errors:
      messages.error(req, error)
    return redirect('products:new')
  # create the product if there are no errors
  Product.objects.create_product(req.POST, req.session['user_id'])
  return redirect('products:index')

def update(req, product_id):
  errors = Product.objects.validate(req.POST)
  if errors:
    for error in errors:
      messages.error(req, error)
    return redirect('products:edit', product_id=product_id)

  Product.objects.update(req.POST, product_id)
  return redirect('products:index')

def delete(req, product_id):
  try:
    product = Product.objects.get(id=product_id)
    product.delete()
  except ObjectDoesNotExist:
    print('TRIED TO DELETE PRODUCT #{}, DOES NOT EXIST'.format(product_id))
  return redirect('products:index')

apps/products/templates/products/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>Edit {{ product.name }}</h1>
    <a href="{% url 'products:index' %}" class="button">Home</a>
    <a href="{% url 'users:logout' %}" class="button">Logout</a>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    <form action="{% url 'products:update' product.id %}" method="post">
      {% csrf_token %}
      <label for="name">Name:</label>
      <input type="text" name="name" placeholder="Socks" value="{{ product.name }}">
      <label for="num_available">Items In Stock:</label>
      <input type="number" name="num_available" placeholder="5" value="{{ product.num_available }}">
      <label for="price">Price:</label>
      <input type="number" name="price" placeholder="5.00" step="0.01" value="{{ product.price }}">
      <label for="description">Description:</label>
      <textarea name="description" id="" cols="30" rows="10">{{ product.description }}</textarea>
      <input type="submit" value="Edit Product">
    </form>
  </div>
</body>
</html>

apps/products/templates/products/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>Hello {{ user.first_name }}</h1>

        <a href="{% url 'products:new' %}" class="button">Create Product</a>
        <a href="{% url 'orders:index' %}" class="button">View Orders</a>
        <a href="{% url 'orders:cart' %}" class="button">View Cart</a>
        <a href="{% url 'users:logout' %}" class="button">Logout</a>

    <div class="purchasable">
      <h2>Products Available For Purchase</h2>

      <table>

        <thead>
          <tr>
            <th>Name</th>
            <th>Num Available</th>
            <th>Price</th>
            <th>Description</th>
            <th>Creator</th>
            <th>Actions</th>
          </tr>

        </thead>

        <tbody>
          {% for product in purchasable_products %}
            <tr>
              <td>
                <a href="{% url 'products:show' product.id %}">{{ product.name }}</a>
              </td>
                <td>{{ product.num_available }}</td>
                <td>${{ product.price }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.creator.first_name }} {{ product.creator.last_name }}</td>
                <td>
                <form action="{% url 'orders:add_product' %}" method="post">
                  {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input type="submit" value="Add To Cart">

                </form>

            </td>

            </tr>

          {% endfor %}

        </tbody>

      </table>

    </div>

    <div class="sellable">
      <h2>Products You're Selling</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Num Available</th>
            <th>Price</th>
            <th>Description</th>
            <th>Creator</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for product in user.products.all %}
            <tr>
              <td>
                <a href="{% url 'products:show' product.id %}">{{ product.name }}</a>
              </td>
              <td>{{ product.num_available }}</td>
              <td>${{ product.price }}</td>
              <td>{{ product.description }}</td>
              <td>{{ product.creator.first_name }} {{ product.creator.last_name }}</td>
              <td>
                <a href="{% url 'products:edit' product.id %}" class="button">Edit Product</a>
                <form action="{% url 'products:delete' product.id %}" method="post">
                  {% csrf_token %}
                  <input type="submit" value="Delete Product">
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>
</html>

apps/products/templates/products/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  {% block head %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="container">
    <h1>Hello {{ user.first_name }}</h1>
    <a href="{% url 'products:new' %}" class="button">Create Product</a>
    <a href="{% url 'orders:index' %}" class="button">View Orders</a>
    <a href="{% url 'orders:cart' %}" class="button">View Cart</a>
    <a href="{% url 'users:logout' %}" class="button">Logout</a>
    {% block body %}{% endblock %}
  </div>
</body>

</html>

apps/products/templates/products/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>Create A Product</h1>
    <a href="{% url 'products:index' %}" class="button">Home</a>
    <a href="{% url 'users:logout' %}" class="button">Logout</a>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    <form action="{% url 'products:create' %}" method="post">
      {% csrf_token %}
      <label for="name">Name:</label>
      <input type="text" name="name" placeholder="Socks">
      <label for="num_available">Items In Stock:</label>
      <input type="number" name="num_available" placeholder="5">
      <label for="price">Price:</label>
      <input type="number" name="price" placeholder="5.00" step="0.01">
      <label for="description">Description:</label>
      <textarea name="description" id="" cols="30" rows="10"></textarea>
      <input type="submit" value="Add Product">
    </form>
  </div>
</body>
</html>

apps/products/templates/products/show.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css"
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>{{ product.name }}</h1>
    <ul>
      <li>Num Available: {{ product.num_available }}</li>
    </ul>
  </div>
</body>
</html>